name: Botni Tekshirish  # Robotning nomi

on: [push]  # Har safar kod yuklaganingda ishga tushsin

jobs:
  check-code:
    runs-on: ubuntu-latest  # Tekshiruv Ubuntu muhitida bo'lsin
    steps:
      - uses: actions/checkout@v3 # Kodni yuklab olish
      - name: Pythonni sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Skriptni yurgizib ko'rish
        run: python main.py