name: Botni Tekshirish
on: [push]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pythonni sozlash
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Skriptni yurgizib ko'rish
        run: python main.py